version: '3.8'
services:
  angular:
    build: front
    ports:
      - "4200:4200"
  express:
    build: back
    ports: 
      - "3000:3000"
    links:
      - bdd
  bdd:
    image: mongo
    ports:
      - "27017:27017"